name: Package and Release with PyInstaller

on:
  push:
    branches:
      - main
      - 'v*'  # This triggers the workflow for version tags
  pull_request:
    branches:
      - main

jobs:
  package:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9]  # Adjust Python version as needed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install pyinstaller speedtest-cli

    - name: Package with PyInstaller
      run: |
        pyinstaller --onefile internet_speed_test.py

    - name: Upload packaged artifact
      uses: actions/upload-artifact@v3
      with:
        name: packaged-app-${{ matrix.os }}
        path: dist/internet_speed_test${{ matrix.os == 'windows-latest' && '.exe' || '' }}

  release:
    runs-on: ubuntu-latest
    needs: package
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: packaged-app-ubuntu-latest
        path: artifacts/ubuntu-latest

    - name: Download artifacts for macOS
      uses: actions/download-artifact@v3
      with:
        name: packaged-app-macos-latest
        path: artifacts/macos-latest

    - name: Download artifacts for Windows
      uses: actions/download-artifact@v3
      with:
        name: packaged-app-windows-latest
        path: artifacts/windows-latest

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload Release Asset (Ubuntu)
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifacts/ubuntu-latest/internet_speed_test
        asset_name: internet_speed_test_ubuntu
        asset_content_type: application/octet-stream

    - name: Upload Release Asset (macOS)
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifacts/macos-latest/internet_speed_test
        asset_name: internet_speed_test_macos
        asset_content_type: application/octet-stream

    - name: Upload Release Asset (Windows)
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifacts/windows-latest/internet_speed_test.exe
        asset_name: internet_speed_test_windows.exe
        asset_content_type: application/octet-stream
